# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='my.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08my.proto\"!\n\x03led\x12\x0b\n\x03Pin\x18\x01 \x02(\x05\x12\r\n\x05\x43olor\x18\x02 \x02(\x05\"F\n\x07\x64isplay\x12\x13\n\x05\x66rame\x18\x01 \x03(\x0b\x32\x04.led\x12\x12\n\x03Ini\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x12\n\x03\x46in\x18\x03 \x01(\x08:\x05\x66\x61lse'
)




_LED = _descriptor.Descriptor(
  name='led',
  full_name='led',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Pin', full_name='led.Pin', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Color', full_name='led.Color', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=45,
)


_DISPLAY = _descriptor.Descriptor(
  name='display',
  full_name='display',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='display.frame', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Ini', full_name='display.Ini', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Fin', full_name='display.Fin', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=117,
)

_DISPLAY.fields_by_name['frame'].message_type = _LED
DESCRIPTOR.message_types_by_name['led'] = _LED
DESCRIPTOR.message_types_by_name['display'] = _DISPLAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

led = _reflection.GeneratedProtocolMessageType('led', (_message.Message,), {
  'DESCRIPTOR' : _LED,
  '__module__' : 'my_pb2'
  # @@protoc_insertion_point(class_scope:led)
  })
_sym_db.RegisterMessage(led)

display = _reflection.GeneratedProtocolMessageType('display', (_message.Message,), {
  'DESCRIPTOR' : _DISPLAY,
  '__module__' : 'my_pb2'
  # @@protoc_insertion_point(class_scope:display)
  })
_sym_db.RegisterMessage(display)


# @@protoc_insertion_point(module_scope)
